### ISSUE TITLE
Deprecated selector in `language-marko/styles/index.atom-text-editor.less`

### ISSUE THREAD

**Issue by Eldar-X** [marko-js/atom-language-marko#10]
In `language-marko/styles/index.atom-text-editor.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `.marko-tag,
.marko-attribute` => `.syntax--marko-tag,
.syntax--marko-attribute`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by DylanPiercey** [comment]
The plugin was reworked to use our Language Server implementation. This should be fixed now.
