### ISSUE TITLE
Commenting shortcut

### ISSUE THREAD

**Issue by mlrawlings** [marko-js/atom-language-marko#12]
Reported by @flyball:

Given a `*.marko` file:
```html
<script>
    var foo;
</script>

<div></div>
```

When I highlight, `<div></div>` and press `⌘` + `/`, I get html style comments:
```html
<script>
    var foo;
</script>

<!-- <div></div> -->
```

But when I highlight, `var foo;` and press `⌘` + `/`, I ***still*** get html style comments:

```html
<script>
    <!-- var foo; -->
</script>

<div></div>
```

I would expect to get JS style comments as I do in `*.html` files.

**Comment by DylanPiercey** [comment]
This is now fixed
