### ISSUE TITLE
scriptlets highlighting broken

### ISSUE THREAD

**Issue by steebchen** [marko-js/atom-language-marko#14]
When using scriptlets, the syntax highlighting below is broken:
![selection_999 1428](https://cloud.githubusercontent.com/assets/5013932/22487447/b4e79e64-e80d-11e6-9cfa-444624ead193.png)

I tried using %/> as closing tag – which works:

![selection_999 1429](https://cloud.githubusercontent.com/assets/5013932/22487899/93406762-e80f-11e6-9069-a0bb072e392d.png)

but it throws this error:

```
Error: An error occurred while trying to compile template at path "/home/luca/websites/video/views/video.html". Error(s) in template:
1) [views/video.html:57:12] EOF reached while parsing scriptlet

    at Compiler.compile (/home/luca/websites/video/node_modules/marko/compiler/Compiler.js:124:25)
    at Object.compile (/home/luca/websites/video/node_modules/marko/compiler/index.js:116:25)
    at compile (/home/luca/websites/video/node_modules/marko/node-require.js:54:38)
    at Object.markoExtension [as .html] (/home/luca/websites/video/node_modules/marko/node-require.js:116:27)
```

It worked perfectly with %> as closing tag with the old atom plugin.
I don't know if this is an issue with the atom plugin or marko itself..

language-marko v2.6.2
tested with marko@3.11.4 & marko@3.14.1, 3.11.4

**Comment by patrick-steele-idem** [comment]
/cc @mlrawlings 

Investigating... thank you for reporting the problem.

**Comment by patrick-steele-idem** [comment]
`<% console.log('Hello'); %>` is still the way to go. I have published a new version of the Atom plugin that fixes the syntax highlighting. Please let us know if you see any other issues.

**Comment by steebchen** [comment]
That was quick. Works like a charm, thanks!
