### ISSUE TITLE
background color styles

### ISSUE THREAD

**Issue by yomed** [marko-js/atom-language-marko#3]
Giving atom another whirl... The marko background-color styling seems strange, and it's usefulness probably depends a lot on the current theme applied. Are there guidelines in trying to reuse colors from the currently applied theme? Otherwise I could just change the colors locally for myself.

![screen shot 2016-03-02 at 2 50 03 pm](https://cloud.githubusercontent.com/assets/3595986/13478480/12b456da-e086-11e5-9044-a5c50516a906.png)

**Comment by patrick-steele-idem** [comment]
I was trying to bring extra emphasis to a important parts. If others find it ugly/distracting/annoying, we can easily remove them. Making the import parts bold and a different fg color is probably sufficient.

Thoughts @philidem?

**Comment by patrick-steele-idem** [comment]
There are less variables, but I am not sure any are suitable for highlighting text. I'll look into it.

**Comment by patrick-steele-idem** [comment]
There is a `@background-color-highlight` variable: https://github.com/atom/atom/blob/master/static/variables/ui-variables.less#L20

That is similar to what this package is doing: https://github.com/marko-js/atom-language-marko/blob/master/styles/index.atom-text-editor.less#L14

**Comment by patrick-steele-idem** [comment]
Here's a theme that sets those variables:
https://github.com/atom/atom-dark-ui/blob/master/styles/ui-variables.less

**Comment by yomed** [comment]
Interesting, I suppose we could use that variable. I think the background color styling is a bit weird in general, but I'm not sure how to change text color without conflicting with other syntax highlighting.

**Comment by patrick-steele-idem** [comment]
Adding a background highlight should look fine with any theme. Do you think the background highlight adds value or should we just get rid of it?

**Comment by yomed** [comment]
I think we should do _something_ (not background highlight), I'm just not sure what. I'll play around with it a bit.

**Comment by patrick-steele-idem** [comment]
You can clone the repo and run `apm link` to install the package as a link back to your cloned project. You can then edit the .less file to try out different combinations (bold, underline, etc.). You need to reload the window to see the changes unfortunately.

**Comment by philidem** [comment]
I actually like the subtle background highlighting. It's not the most aesthetically pleasing but I like that it stands out.

**Comment by yomed** [comment]
Any opposition to just using colors from the theme? They seem to look fine, and fit in with whatever theme is being used. I just tried with some the vars from here: https://github.com/atom/atom/blob/master/static/variables/syntax-variables.less

```
@syntax-color-variable
@syntax-color-tag
@syntax-color-attribute
```

**Comment by seangates** [comment]
+1 for using any colors already in the available theme.

**Comment by patrick-steele-idem** [comment]
@yomed I'm not opposed, but I haven't had a chance to try it out. Do you want to send a PR with the combination that you think works best?
